### ISSUE TITLE
Application outdated for use.

### ISSUE THREAD

**Issue by NeniEmSu** [OpenClassrooms-Student-Center/5614116-go-fullstack-recipe-frontend#3]
1. Your global Angular CLI version (8.3.6) is greater than your localversion (6.2.4). The local Angular CLI version is used.

2. Unable to compile
```
ERROR in ./src/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
Require stack:
- D:\Projects\fullstack-app\recipe-frontend\node_modules\sass-loader\lib\loader.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\loader-runner\lib\loadLoader.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\loader-runner\lib\LoaderRunner.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\NormalModule.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\NormalModuleFactory.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\Compiler.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\webpack.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\build-webpack\src\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\architect\src\architect.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\architect\src\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\models\architect-command.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\commands\serve-impl.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\schematics\tools\export-ref.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\schematics\tools\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\models\command-runner.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\emman\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\emman\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)     
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.sassLoader (D:\Projects\fullstack-app\recipe-frontend\node_modules\sass-loader\lib\loader.js:46:72)
ERROR in ./src/app/app.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
Require stack:
- D:\Projects\fullstack-app\recipe-frontend\node_modules\sass-loader\lib\loader.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\loader-runner\lib\loadLoader.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\loader-runner\lib\LoaderRunner.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\NormalModule.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\NormalModuleFactory.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\Compiler.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\webpack.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\build-webpack\src\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\architect\src\architect.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\architect\src\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\models\architect-command.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\commands\serve-impl.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\schematics\tools\export-ref.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\schematics\tools\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\models\command-runner.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\emman\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\emman\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)     
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.sassLoader (D:\Projects\fullstack-app\recipe-frontend\node_modules\sass-loader\lib\loader.js:46:72)
ERROR in ./src/app/recipe-list/recipe-list.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
Require stack:
- D:\Projects\fullstack-app\recipe-frontend\node_modules\sass-loader\lib\loader.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\loader-runner\lib\loadLoader.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\loader-runner\lib\LoaderRunner.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\NormalModule.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\NormalModuleFactory.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\Compiler.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\webpack.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\build-webpack\src\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\architect\src\architect.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\architect\src\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\models\architect-command.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\commands\serve-impl.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\schematics\tools\export-ref.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\schematics\tools\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\models\command-runner.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\emman\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\emman\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)     
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.sassLoader (D:\Projects\fullstack-app\recipe-frontend\node_modules\sass-loader\lib\loader.js:46:72)
ERROR in ./src/app/single-recipe/single-recipe.component.scss     
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
Require stack:
- D:\Projects\fullstack-app\recipe-frontend\node_modules\sass-loader\lib\loader.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\loader-runner\lib\loadLoader.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\loader-runner\lib\LoaderRunner.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\NormalModule.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\NormalModuleFactory.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\Compiler.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\webpack.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\build-webpack\src\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\architect\src\architect.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\architect\src\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\models\architect-command.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\commands\serve-impl.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\schematics\tools\export-ref.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\schematics\tools\index.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\models\command-runner.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\emman\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\emman\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)     
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.sassLoader (D:\Projects\fullstack-app\recipe-frontend\node_modules\sass-loader\lib\loader.js:46:72)
ERROR in ./src/app/recipe-form/recipe-form.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
Require stack:
- D:\Projects\fullstack-app\recipe-frontend\node_modules\sass-loader\lib\loader.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\loader-runner\lib\loadLoader.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\loader-runner\lib\LoaderRunner.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\NormalModule.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\NormalModuleFactory.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\Compiler.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\webpack\lib\webpack.js
- D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)     
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.sassLoader (D:\Projects\fullstack-app\recipe-frontend\node_modules\sass-loader\lib\loader.js:46:72)
i ｢wdm｣: Failed to compile.
```
3. After audit fix
Contains breaking changes

```
+ @angular-devkit/build-angular@0.803.6
added 327 packages from 127 contributors, removed 97 packages, updated 159 packages and moved 12 packages in 393.368s
fixed 606 of 608 vulnerabilities in 39130 scanned packages        
  2 package updates for 2 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
```

4. $ ng serve

```
Your global Angular CLI version (8.3.6) is greater than your localversion (6.2.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:        
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber.project (D:\Projects\fullstack-app\recipe-frontend\node_modules\@angular-devkit\core\src\workspace\workspace.js:210:42)
    at MergeMapSubscriber._tryNext (D:\Projects\fullstack-app\recipe-frontend\node_modules\rxjs\internal\operators\mergeMap.js:65:27)
    at MergeMapSubscriber._next (D:\Projects\fullstack-app\recipe-frontend\node_modules\rxjs\internal\operators\mergeMap.js:55:18)  
    at MergeMapSubscriber.Subscriber.next (D:\Projects\fullstack-app\recipe-frontend\node_modules\rxjs\internal\Subscriber.js:64:18)    at MergeMapSubscriber.notifyNext (D:\Projects\fullstack-app\recipe-frontend\node_modules\rxjs\internal\operators\mergeMap.js:84:26)
    at InnerSubscriber._next (D:\Projects\fullstack-app\recipe-frontend\node_modules\rxjs\internal\InnerSubscriber.js:25:21)        
    at InnerSubscriber.Subscriber.next (D:\Projects\fullstack-app\recipe-frontend\node_modules\rxjs\internal\Subscriber.js:64:18)   
    at MapSubscriber._next (D:\Projects\fullstack-app\recipe-frontend\node_modules\rxjs\internal\operators\map.js:52:26)
    at MapSubscriber.Subscriber.next (D:\Projects\fullstack-app\recipe-frontend\node_modules\rxjs\internal\Subscriber.js:64:18)     
    at SwitchMapSubscriber.notifyNext (D:\Projects\fullstack-app\recipe-frontend\node_modules\rxjs\internal\operators\switchMap.js:77:26)
```

**Comment by uxFeranmi** [comment]
Having the same issue.

**Comment by NeniEmSu** [comment]
A quick fix is to clone the repo, then run
npm install && npm I node-sass && ng serve 
To get to use the frontend for basic testing.
Ignore the warnings.

**Comment by uxFeranmi** [comment]
Ok thanks. Thanks a lot.

**Comment by uxFeranmi** [comment]
Note: Need to install nodes-sass@4.12.0 if you have node version 12 installed.

**Comment by willehpeh** [comment]
You can simply force a node-sass rebuild, as is often necessary when a project was built with a different version of Node to the local version.

Sent from my iPhone

On 1 Oct 2019, at 13:16, Akinlade Feranmi <notifications@github.com<mailto:notifications@github.com>> wrote:


Note: Need to install nodes-sass@4.12.0 if you have node version 12 installed.

**Comment by JeffOgah** [comment]
Perhaps this should be included in the readme as well to make it easier to quickly get the app running
